services:
  app:
    build:
      context: .
    image: video-generation-tool
    container_name: video-generation-tool-${USER}
    ports:
      - "5000:5000"
    volumes:
      - /home/mingchin/video_generation/data_pipeline/clips:/app/clips
      - ./data:/app/data
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_ENV=development
